### ISSUE TITLE
Sobre integração

### ISSUE THREAD

**Issue by mozgbrasil** [byjg/omnipay-komerci#2]
Ola

Bom dia

Vejo em outras integrações que é usado os recursos de confirmação de autorização e comprovante de Venda

Esses recursos não é necessário para a integração a Redecard ?

**Comment by byjg** [comment]
Ola, 

Como ele usa o Omnipay, segue a interface desse framework para fazer o processo. 

No exemplo do Readme ele faz a autorização e captura imediatamente (que é o método PURCHASE)

Caso vc queira fazer a autorização e captura em duas etapas pode fazer isso:

``` php
// Setup payment gateway
$gateway = Omnipay::create('Komerci');
$gateway->setApiKey('00000000');
$gateway->setUsername('user');
$gateway->setPassword('pass');
$gateway->setTestMode(true);

// Example form data
$formData = [
    'name' => 'Joao Magalhaes',
    'number' => '4242424242424242',
    'expiryMonth' => '6',
    'expiryYear' => '2016',
    'cvv' => '123'
];

// Send purchase request
$response = $gateway->authorize(
    [
        'amount' => '10.00',
        'transactionId' => '1234',
        'card' => $formData,
    ]
)->send();

if (!$response->isSucessfull) {
    throw new \Exception('Falhou a Autorização - ' . $response->getMessage());
}

// Faz a captura
$responseCapture = $gateway->capture(
    [
        'amount' => '10.00',
        'transactionReference' => $response->getTransactionReference(),
        'numautor' => $response->getNumAutor(),
    ]
)->send();

if (!$responseCapture->isSucessfull()) {
    throw new \Exception('Falhou a Captura - ' . $response->getMessage());
}

// Imprime o comprovante de vendas
echo $responseCapture->getSalesSlip();

```

Ao utilizar o Omnipay você tem uma interface padronizada para capturar as transações o que diminui em muito a complexidade para implementar novos drives. 

Sugiro fortemente que você veja a documentação do Omnipay para entender como funciona.

http://omnipay.thephpleague.com/

**Comment by mozgbrasil** [comment]
Ola Bom dia

Na tentativa de executar esse exemplo ou o exemplo do repositório está sendo retornado o erro

Fatal error:  Uncaught Error: Class 'Omnipay' not found in

Pode me informar como devo corrigir essa ocorrência 

![captura de tela de 2017-02-09 11-38-39](https://cloud.githubusercontent.com/assets/17202780/22785943/859e9818-eebd-11e6-9108-cb843c1a1f4a.png)
![captura de tela de 2017-02-09 11-46-42](https://cloud.githubusercontent.com/assets/17202780/22785944/859eea52-eebd-11e6-8bfc-5e4995feeaf5.png)
![captura de tela de 2017-02-09 11-46-51](https://cloud.githubusercontent.com/assets/17202780/22785945/85a45c9e-eebd-11e6-933d-8620b320caca.png)

**Comment by mozgbrasil** [comment]
Acabei encontrando 

Tinha que usar antes

use Omnipay\Omnipay;

**Comment by byjg** [comment]
Que ótimo ! Foi mal não ter passado o namespace completo. Se tiver tudo direitinho eu fecho esse Issue, ok?

**Comment by byjg** [comment]
Fechando Issue!
